version: 2

# Modulos Alessandra
sphinx:
  configuration: analise_alessandra/docs/conf.py
python:
  version: 3.7
build:
    os: ubuntu-22.04

# Modulos Edgard
sphinx:
  configuration: analise_edgard/docs/conf.py
python:
  version: 3.7
build:
    os: ubuntu-22.04

# Modulos Guilherme
sphinx:
  configuration: analise_guilherme/docs/conf.py
python:
  version: 3.7
build:
    os: ubuntu-22.04

# Modulos Jeann
sphinx:
  configuration: analise_jeann/docs/conf.py
python:
  version: 3.7
build:
    os: ubuntu-22.04
