version: 2

# Modulo Alessandra
- sphinx:
    configuration: analise_alessandra/docs/conf.py
  python:
    version: 3.7
  build:
    os: ubuntu-22.04
    tools:
      - make
    commands:
      - make html

# Modulo Edgard
- sphinx:
    configuration: analise_edgard/docs/conf.py
  python:
    version: 3.7
  build:
    os: ubuntu-22.04
    tools:
      - make
    commands:
      - make html

# Modulo Guilherme
- sphinx:
    configuration: analise_guilherme/docs/conf.py
  python:
    version: 3.7
  build:
    os: ubuntu-22.04
    tools:
      - make
    commands:
      - make html

# Modulo Jeann
- sphinx:
    configuration: analise_jeann/docs/conf.py
  python:
    version: 3.7
  build:
    os: ubuntu-22.04
    tools:
      - make
    commands:
      - make html
